services:
  latex:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app  # Mount the current directory to `/app` in the container
    working_dir: /app
    stdin_open: true
    tty: true
